version = 1

[[annotations]]
path = ["TemplateApplication.xcodeproj/**", "TemplateApplication/Resources/**", "TemplateApplication/Supporting Files/**"]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"