#
# This source file is part of the Stanford Spezi Template Application open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: Beta-Deployment
  cancel-in-progress: false

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
    secrets: inherit
  staticanaylsis:
    name: Static Analysis
    uses: ./.github/workflows/static-analysis.yml
    permissions:
      security-events: write
      actions: read
      contents: read
    secrets: inherit
  iosapptestflightdeployment:
    name: iOS App TestFlight Deployment
    needs: buildandtest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      contents: read
    with:
      googleserviceinfoplistpath: 'TemplateApplication/Supporting Files/GoogleService-Info.plist'
      setupsigning: true
      fastlanelane: beta
    secrets: inherit
  deployfirebase:
    name: Deploy Firebase Project
    needs: iosapptestflightdeployment
    uses: StanfordBDHG/.github/.github/workflows/firebase-deploy.yml@v2
    permissions:
      contents: read
    with:
      arguments: '--debug'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
